<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
            background-image: url(https://d2g7iw15geyppn.cloudfront.net/images/fake/bg01.jpg);
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }

        h2 {
            color: black;
         
            font-family: 'Lato', sans-serif;
            font-size: 20px;
            font-weight: 200;
            margin-bottom: 0;
        }
    

    </style>
</head>

<body>
    <h1>SimplesVet</h1>
    <div>a microframework for PHP</div>

    <?php if (isset($pet)): ?>
    <table>
        <?php foreach ($pet as $key => $value) { ?>
        <tr>
            <td>
               <h2>  <?php echo $value->nome; ?> </h2>
            </td>
            <td>
               <h2>  <?php echo $value->raca->nome; ?> </h2>
            </td>
        </tr>
        <?php 
    } ?>
    </table>
    <?php else: ?>
    <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>
    <?php endif; ?>
</body>

</html> 